name: Build Next.js Project

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: Deploy to Vercel
        required: true
        default: true
        type: boolean
      os:
        description: Operating system to build on
        required: true
        default: Windows
        type: choice
        options:
          - Ubuntu
          - Windows
          - macOS
      debug:
        description: Enable Vercel debug mode
        required: false
        default: true
        type: boolean

  push:
    branches: [master, preview]
    paths:
      - 'src/**'
      - 'public/**'
      - 'next.config.ts'
      - 'package*.json'
      - 'tsconfig.json'
      - 'tailwind.config.js'
      - 'postcss.config.js'

permissions:
  contents: write

jobs:
  build:
    concurrency: vercel-ci/${{ github.ref_name }}
    runs-on: ${{ inputs.os || 'Windows' }}-latest
    env:
      NODE_VERSION: 22.x
      VERCEL_ENV: ${{ (github.ref_name == 'master') && 'production' || 'preview' }}
      VERCEL_TARGET_ENV: ${{ (github.ref_name == 'master') && 'production' || 'preview' }}
      VERCEL_PREVIEW_DOMAIN: wattbreaker-preview.vercel.app
      PROD: ${{ (github.ref_name == 'master') && '--prod' || '' }}
      DEBUG: ${{ (inputs.debug == true || github.event_name == 'push') && '--debug' || '' }}
      DEPLOY: ${{ ((github.event_name == 'workflow_dispatch' && inputs.deploy == true) || github.event_name == 'push') && 'true' || 'false' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Setup Vercel CLI
        run: npm install -g vercel
      - name: Link Vercel project
        run: vercel link ${{ env.DEBUG }} --token ${{ secrets.VERCEL_TOKEN }} --project ${{ secrets.VERCEL_PROJECT_NAME }} --yes
      - name: Pull Vercel project settings
        run: vercel pull ${{ env.DEBUG }} --token ${{ secrets.VERCEL_TOKEN }} --yes

      - name: Build project
        run: vercel build ${{ env.DEBUG }} ${{ env.PROD }} --token ${{ secrets.VERCEL_TOKEN }} --yes

      - name: Run tests
        run: npm test

      - name: Deploy to Vercel
        if: env.DEPLOY == 'true'
        run: |
          vercel deploy --prebuilt ${{ env.DEBUG }} ${{ env.PROD }} --token ${{ secrets.VERCEL_TOKEN }} --regions ${{ secrets.VERCEL_REGIONS }} --yes > deployment-url.txt
          echo "::notice::Deployment URL: $(cat deployment-url.txt)"
          if [ $VERCEL_ENV == 'preview' ]; then
            vercel alias set $(cat deployment-url.txt) ${{ env.VERCEL_PREVIEW_DOMAIN }} ${{ env.DEBUG }} --token ${{ secrets.VERCEL_TOKEN }}
          fi
        shell: bash
